Kfbsd v3 Code working for ARM FreeBSD Kernel.
yale-systems/sqlite pull request #5
Opened 2024-01-16 16:20 UTC by stelkasouridis

Several modifications were made to work with ARM FreeBSD Kernel. The code is tested and works successfully with a FreeBSD Kernel module.

Only required steps are:

sudo mkdir bld
cd bld
sudo ../configure --host=arm-kfbsd
sudo make sqlite3-all.c

2024-01-16 19:12 UTC, robertsoule requested changes
Stelios, can you please add code to emit warnings for code paths where you have not yet implemented the logic? If we don't have some sort of indication, then we might falsely assume that the code is working.

2024-01-16 19:12 UTC, robertsoule commented on src/date.c
> +  sqlite3_result_text(context, zBuf, -1, SQLITE_TRANSIENT);
@stelkasouridis : while I think it is okay to stub out functionality for now, I am worried that this has a potential to fail silently. I think you need to add some code here to either emit trace that this should not be called or to initiate some type of failure/assertion.

2024-01-16 19:12 UTC, robertsoule commented on src/expr.c
> +        //todo: STELIOS
@stelkasouridis : It seems like you should emit some warning here that the code isn't ready yet.

2024-01-16 19:12 UTC, robertsoule commented on src/func.c
> +  //todo: STELIOS
@stelkasouridis : should you also emit a warning of fail if this code path is traversed?

2024-01-16 19:12 UTC, robertsoule commented on src/os.c
> +    //todo: STELIOS
Emit warning?

2024-01-16 19:12 UTC, robertsoule commented on src/os_kfbsd.c
> +  /* TODO: Implement FreeBSD-specific initialization here. */
What functionality should go here? Should you emit a warning that this is not yet done? Why don't you need to have something here in order for your demo to work?

2024-01-16 19:12 UTC, robertsoule commented on src/os_kfbsd.c
> +                         int flags, int *pOutFlags) {
Fix the formatting?

2024-01-16 19:12 UTC, robertsoule commented on src/os_kfbsd.h
> +    //todo: STELIOS
@stelkasouridis : can you please emit a warning if these methods are called? I am worried that they are going to fail silently.

2024-01-16 19:13 UTC, robertsoule commented on ext/misc/amatch.c
> -
@stelkasouridis : can you please revert to the committed version of this code? It looks like you removed a newline, and we don't really want to commit that change.

2024-01-16 19:14 UTC, robertsoule commented on ext/misc/prefixes.c
> +
@stelkasouridis : please revert to committed version of this file. We don't want to commit changes that just include whitespace changes.

2024-01-16 19:40 UTC, stelkasouridis commented on src/date.c
> +  sqlite3_result_text(context, zBuf, -1, SQLITE_TRANSIENT);
Emitted trace that this function should not be called.

2024-01-16 19:53 UTC, robertsoule commented on src/date.c
> +  sqlite3_result_text(context, zBuf, -1, SQLITE_TRANSIENT);
Maybe "currentTimeFunc unimplemented on FreeBSD kernel" is more informative?

2024-01-16 21:58 UTC, gvnn3 requested changes

2024-01-16 21:58 UTC, gvnn3 commented on ext/lsm1/lsm-test/lsmtest_main.c
Seems like this was a whitespace change that you don't need.  Please remove it from the PR.

2024-01-16 21:58 UTC, gvnn3 commented on sqlite_cfg.h.in
Why are lines being removed from this file?  In theory we should only see additions.

2024-01-16 21:58 UTC, gvnn3 commented on src/os.c
I'm a little confused on what this function is supposed to do normally.  Is it just to get a random number or to seed a random number generator?  The kernel has a source of randomness that can be used if it's required here.

2024-01-16 23:01 UTC, robertsoule commented on configure.ac
> -AC_SUBST(HAVE_ZLIB)
Why are these lines removed?

2024-01-16 23:02 UTC, robertsoule commented on sqlite_cfg.h.in
> -
Why is this removed?

2024-01-16 23:03 UTC, robertsoule commented on sqlite_cfg.h.in
> -#endif
Why are these lines removed?

2024-01-18 16:19 UTC, robertsoule approved these changes

2024-01-18 16:20 UTC, gvnn3 approved these changes

2024-05-17 11:25 UTC, closed without merging